### ISSUE TITLE
It's possible to send Image and Text?

### ISSUE THREAD

**Issue by rafaelks** [kikinteractive/kik-api-iphone#4]
Hey,

I can't find any API to send text and image in the same message... Am I missing something?

Thanks!

**Comment by awmwong** [comment]
@rafaelks What do you mean by text and image in the same message? Have you looked at the ```article``` layout methods where you can specify text and a preview image?

**Comment by rafaelks** [comment]
@awmwong Oh, yes. I mean, text and image (UIImage instance).

**Comment by awmwong** [comment]
@rafaelks The `previewURL` field in the `article` message call supports base64 data URIs. You can take your UIImage and convert it to a base64 data URI and pass that through there. Though do note you will be limited to certain image size restrictions if you do so this way.

**Comment by rafaelks** [comment]
@awmwong OK, thank you!
