### ISSUE TITLE
share to kik is not working

### ISSUE THREAD

**Issue by samiq** [kikinteractive/kik-api-iphone#9]
Hi guys, I realize this pod hasn't been updated in a long while and it no longer shares to the app, it only opens the appstore for the user to install the app rather than opening the app with the message.

any chance you will update this and keep the pod up to date?

**Comment by michaelforrest** [comment]
+1 - I'm trying out this library today and it just links to the App Store.

**Comment by michaelforrest** [comment]
Ok this is a simple fix - just add `kik-share` to `LSApplicationQueriesSchemes` in your `Info.plist`. This should be included in the documentation though, so it's still a bug.
